datadog:
  site: "datadoghq.com"
  clusterName: "your-cluster-name-here"
  apiKeyExistingSecret: "datadog-secret"
  clusterChecks:
    enabled: true
  orchestratorExplorer:
    enabled: true
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            # java: "1"
            # python: "3"
            # js: "5"
            # php: "1"
            dotnet: "3"
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true

# Security Section (disable if not required)
  securityAgent:
    # Enables Workload Protection
    runtime:
      enabled: true
    # Enables Misconfigurations
    compliance:
      enabled: true
      host_benchmarks:
        enabled: true
  sbom:
    containerImage:
      enabled: true
      # should be set to true when using EKS, GKE or if containerd is configured to
      # discard uncompressed layers.
      uncompressedLayersSupport: true
    # Enables Host Vulnerability Management
    host:
      enabled: true

remoteConfiguration:
  enabled: true
